- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.1
  hooks:
  - id: trailing-whitespace
  - id: debug-statements
  - id: fix-encoding-pragma
  - id: flake8
  - id: check-merge-conflict
    exclude: "migrations/*"

- repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
  sha: v0.0.2
  hooks:
  - id: pydocstyle
    exclude: "(migrations/*|tests/*)"
    args: ['--ignore=D100,D105,D203,D400']

- repo: git://github.com/pricematch/pricematch-pre-commit-hooks
  sha: 82b0c142b363547cc873bc6581fa3074087a37d2
  hooks:
  - id: do_not_commit
